/-
This file was generated by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 7e6e0067-adf6-4798-a305-2052664292a6
-/

/-
We prove that the volume of the unit hypercube `F` in `EuclideanSpace ℝ (Fin n)` is 1.
The set `F` is defined as the product of `n` intervals `[0, 1)`.
We use the fact that `EuclideanSpace.measurableEquiv` is volume-preserving to transfer the calculation to the standard product measure on `Fin n → ℝ`.
Then we use `Real.volume_pi_Ico` to show that the volume is the product of the lengths of the intervals, which is `1^n = 1`.
-/
import Mathlib.MeasureTheory.Measure.Haar.InnerProductSpace

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

#check EuclideanSpace

#check Real
#check MeasureTheory.volume

#print EuclideanSpace
#print PiLp

#print WithLp

#check EuclideanSpace.volume_preserving_measurableEquiv
#check Real.volume_pi_Ico

variable {n : Nat}
example (x : EuclideanSpace ℝ (Fin n)) : EuclideanSpace.measurableEquiv (Fin n) x = x := by rfl

/-
The volume of the unit hypercube F in Euclidean space is 1.
-/
open MeasureTheory Set
variable {n : Nat}
abbrev E (n : Nat) := EuclideanSpace ℝ (Fin n)
def F (n : Nat) : Set (E n) := Set.pi Set.univ (fun _ => Ico 0 1)
theorem volume_F : volume (F n) = 1 := by
  -- The volume of the unit hypercube in Euclidean space is given by the product of the lengths of its sides, which is 1.
  have h_volume : MeasureTheory.volume (Set.pi Set.univ fun _ : Fin n => Set.Ico (0 : ℝ) 1) = 1 := by
    erw [ Real.volume_pi_Ico ] ; norm_num;
  convert h_volume using 1;
  convert ( EuclideanSpace.volume_preserving_measurableEquiv ( Fin n ) |> MeasureTheory.MeasurePreserving.measure_preimage ) _;
  · exact rfl;
  · exact MeasurableSet.nullMeasurableSet ( by exact MeasurableSet.univ_pi fun _ => measurableSet_Ico )


#min_imports
